### ISSUE TITLE
Can't deploy Spring Boot 2.0.0 Application with bound Metrics Forwarder service

### ISSUE THREAD

**Issue by slu-it** [cloudfoundry/java-buildpack-metric-writer#3]
When deploying a Spring Boot `2.0.0.RELEASE` application to Pivotal Web Services (as of 2018-03-07), the application cannot be started because of the following exception:

```
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] java.lang.IllegalStateException: Failed to introspect Class [org.cloudfoundry.metrics.boot2.CloudFoundryMetricWriterAutoConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@1b28cdfa]
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:659)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:556)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:541)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:599)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:728)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:669)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:637)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1489)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:420)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:390)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:511)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:503)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1194)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:866)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:852)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:803)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at library.enrichment.ApplicationKt.main(Application.kt:24)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/autoconfigure/metrics/export/MetricsExporter
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at java.lang.Class.getDeclaredMethods0(Native Method)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at java.lang.Class.getDeclaredMethods(Class.java:1975)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:641)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] ... 28 common frames omitted
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.autoconfigure.metrics.export.MetricsExporter
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2018-03-07T23:12:45.648+01:00 [APP/PROC/WEB/0] [OUT] ... 32 common frames omitted
2018-03-07T23:12:45.772+01:00 [APP/PROC/WEB/0] [OUT] Exit status 1
```

I first noticed this with Spring Boot `2.0.0.RC1`. Without a bound Metrics Forwarder service, deploying the application is no problem.

**Java Build Pack version:**  `4.9`
**Metrics Writer version (from build Pack) :** `2.3.0_RELEASE`

It seams the current build snapshot would fix this issue with commit d489dd5b16e84ffa104744af993755fe0b84ab2c. Is there a date for the next release version?

**Comment by nebhale** [comment]
Yep, they've been making a bunch of breaking changes right down to the wire on both the Micrometer and Boot releases.  I've got most of them handled, and I'm committing the latest ones now for a 2.4.0.RELEASE.

**Comment by slu-it** [comment]
Ok, thanks for the info!

**Comment by nebhale** [comment]
Release complete and it'll make the next buildpack release.
