### ISSUE TITLE
App fails to start if micrometer is present but Spring Boot actuators are not

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/java-buildpack-metric-writer#6]
```
   2019-09-27T09:12:39.55+0100 [APP/PROC/WEB/0] OUT 2019-09-27 08:12:39.553  INFO 7 --- [           main] o.s.g.c.a.ClusterAwareConfiguration      : Failed to connect to localhost[10334]
   2019-09-27T09:12:40.58+0100 [APP/PROC/WEB/0] OUT 2019-09-27 08:12:40.587 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
   2019-09-27T09:12:40.58+0100 [APP/PROC/WEB/0] OUT java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration]
   2019-09-27T09:12:40.58+0100 [APP/PROC/WEB/0] OUT     at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:327) ~[spring-core-5.2.0.RC2.jar:5.2.0.RC2]
   2019-09-27T09:12:40.58+0100 [APP/PROC/WEB/0] OUT     at org.springframework.core.annotation.TypeMappedAnnotation.adapt(TypeMappedAnnotation.java:479) ~[spring-core-5.2.0.RC2.jar:5.2.0.RC2]
   2019-09-27T09:12:40.58+0100 [APP/PROC/WEB/0] OUT     at org.springframework.core.annotation.TypeMappedAnnotation.getValue(TypeMappedAnnotation.java:403) ~[spring-core-5.2.0.RC2.jar:5.2.0.RC2]
```

This is because of the way the conditions are structured in the autoconfig:

```java
@AutoConfigureBefore(value={MetricsAutoConfiguration.class})
@ConditionalOnClass(value={MeterFilter.class})
@ConditionalOnCloudPlatform(value=CloudPlatform.CLOUD_FOUNDRY)
@Configuration
class CloudFoundryTagsMeterFilterAutoConfiguration {
```

**Comment by snicoll** [comment]
Changing the class check as follows should fix it:

```java
@ConditionalOnClass(value={MeterFilter.class, MetricsAutoConfiguration.class})
```
